### ISSUE TITLE
Plan to develop and support

### ISSUE THREAD

**Issue by leech001** [Alezhka/flutter_incoming_call#1]
Hi. Do you plan to develop and support the library (null safety)? As well as publishing it on pub.dev?

**Comment by Alezhka** [comment]
@leech001 Hi! I've published to pub.dev and update the plugin to null safety(See Readme). The plugin still needs some work. As soon as I have more free time I will make some more updates. For example, on android, there is a crash if you make another call on top of the currently active call. I also haven't tested ios yet.

**Comment by leech001** [comment]
Thank you very much! Very much appreciated.
