### ISSUE TITLE
How to integrate Agora sdk with this package

### ISSUE THREAD

**Issue by devDonald** [Alezhka/flutter_incoming_call#4]
Hello, please can you show me how to integrate this plugin to see incoming calls from Agoro sdk in flutter. Any sample code please

**Comment by Alezhka** [comment]
Hi, I did not use this service and deliberately left the right to choose a SDK for making calls outside this library.
In short, the scheme of work is as follows:
1. You must send a push notification about an incoming call. For iOS use VOIP push.
2. Use the data from the push message and this library to display an incoming call. 
3. After opening the application, display your communication interface according to the selected SDK.

**Comment by devDonald** [comment]
Okay. Thank you sir
