### ISSUE TITLE
Hello , How i can bring my app to foregound when user tap on accept button.

### ISSUE THREAD

**Issue by TouseefAQ** [Alezhka/flutter_incoming_call#6]
Hello , I am implementing video calling using agora. Upon receiving fcm i can initiate incoming call using this plugin but when user hits acept screen how i can show calling screen.

Any lead would be appciated .

Thank you !

**Comment by Alezhka** [comment]
If you are talking about ios, then after answering the call, the audio session begins. You can start playing audio. To open your application, you must click on the application icon in the communication interface. Unfortunately, iOS cannot open the application immediately after answering a call.

Android application immediately opens your application after answering an incoming call

**Comment by TouseefAQ** [comment]
Yes , this is what i am talking about. In iOS when user answer the call , can we open the app ? just like android. Because as you know  when fcm arrive and user interact with it , fcm can open the app. So can we acheive same behaviour with some work arrpunds

**Comment by Alezhka** [comment]
I have researched this question, but unfortunately not.

**Comment by alvinotienokelly** [comment]
> Hello , I am implementing video calling using agora. Upon receiving fcm i can initiate incoming call using this plugin but when user hits acept screen how i can show calling screen.
> 
> Any lead would be appciated .
> 
> Thank you !

Hello . Having thesame implementation using agora . Have you managed to solve this?

**Comment by TouseefAQ** [comment]
@alvinotienokelly  I'm still working on it , will let you know if i find any lead.

**Comment by TouseefAQ** [comment]
@Alezhka flutter local notification , allow us to wake up the app both in android and ios , So for future please take reference from these plugin to wake up the app. I found your plugin easy to use.Thank you !

**Comment by manujjagga421** [comment]
@TouseefAQ did you find solution to this.
